export class EdgeSearchService {
    constructor(eventBus) { this.eventBus = eventBus; this.index = []; this.results = []; this.suggestions = []; this.fetcher = null; this.endpoint = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.index = options.index || []; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_EDGE_SEARCH_QUERY', (p) => this.query(p.key || p.data?.query || '', p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_EDGE_SEARCH_SUGGEST', (p) => this.suggest(p.key || p.data?.query || ''))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_EDGE_SEARCH_RESET', () => this.reset())); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async query(query, options = {}) { try { this.results = this.endpoint ? await this.remoteQuery(query, options) : this.localQuery(query); this.eventBus?.publish?.('EDGE_SEARCH_RESULTS', { key: query, items: this.results, data: { count: this.results.length }, timestamp: Date.now() }); return this.results; } catch (error) { this.eventBus?.publish?.('EDGE_SEARCH_ERROR', { key: query, error: error?.message || String(error), timestamp: Date.now() }); return []; } }
    suggest(query) { const normalized = String(query || '').toLowerCase(); this.suggestions = [...new Set(this.index.flatMap((item) => [item.title, ...(item.tags || [])]).filter(Boolean).filter((value) => String(value).toLowerCase().startsWith(normalized)))].slice(0, 8); this.eventBus?.publish?.('EDGE_SEARCH_SUGGESTIONS', { key: query, items: this.suggestions.map((title) => ({ title })), timestamp: Date.now() }); return this.suggestions; }
    localQuery(query) { const normalized = String(query || '').toLowerCase(); return this.index.filter((item) => [item.title, item.body, ...(item.tags || [])].filter(Boolean).some((value) => String(value).toLowerCase().includes(normalized))); }
    async remoteQuery(query, options = {}) { if (!this.fetcher || !this.endpoint) return []; const url = new URL(this.endpoint, globalThis.location?.origin || 'http://localhost'); url.searchParams.set('q', query); for (const [key, value] of Object.entries(options.facets || {})) url.searchParams.set(key, value); const response = await this.fetcher(url.toString(), { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Search failed with ${response.status}`); const data = await response.json(); return Array.isArray(data) ? data : data.items || []; }
    reset() { this.results = []; this.suggestions = []; }
}
