export class AbTestingService {
    constructor(eventBus) { this.eventBus = eventBus; this.assignments = new Map(); this.exposures = []; this.assignEndpoint = null; this.exposureEndpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.assignEndpoint = options.assignEndpoint || options.endpoint || null; this.exposureEndpoint = options.exposureEndpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.experiments = options.experiments || {}; this.seed = options.seed || null; this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_AB_TEST_ASSIGN', (p) => this.assign(p.key || p.id, p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_AB_TEST_EXPOSE', (p) => this.expose(p.key || p.id))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_AB_TEST_RESET', () => this.reset())); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async assignRemote(experimentId, context = {}) { if (!this.assignEndpoint || !this.fetcher) return this.assign(experimentId, context); const response = await this.fetcher(this.assignEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ experimentId, context }) }); if (!response.ok) throw new Error(`Experiment assignment failed with ${response.status}`); const data = await response.json(); const assignment = data.assignment || data; this.assignments.set(experimentId, assignment); return assignment; }
    assign(experimentId, context = {}) { if (!experimentId) return null; const experiment = this.experiments[experimentId] || context; const variants = experiment.variants || null; if (!variants || !Array.isArray(variants) || variants.length === 0) return null; const key = `${this.seed || 'unseeded'}:${experimentId}:${context.userId || 'anonymous'}`; const index = this.hash(key) % variants.length; const assignment = { experimentId, variant: variants[index], reason: experiment.source || 'local-configured' }; this.assignments.set(experimentId, assignment); this.eventBus?.publish?.('AB_TEST_ASSIGNED', { key: experimentId, data: assignment, timestamp: Date.now() }); return assignment; }
    async exposeRemote(experimentId) { const assignment = this.expose(experimentId); if (this.exposureEndpoint && this.fetcher && assignment) { await this.fetcher(this.exposureEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(assignment) }); } return assignment; }
    expose(experimentId) { const assignment = this.assignments.get(experimentId) || this.assign(experimentId); if (!assignment) return null; this.exposures.push({ ...assignment, timestamp: Date.now() }); this.eventBus?.publish?.('AB_TEST_EXPOSURE', { key: experimentId, data: assignment, timestamp: Date.now() }); return assignment; }
    reset() { this.assignments.clear(); this.exposures = []; }
    hash(value) { return [...String(value)].reduce((hash, char) => ((hash << 5) - hash + char.charCodeAt(0)) >>> 0, 0); }
}
