export class ImportExportService {
    constructor(eventBus) { this.eventBus = eventBus; this.preview = null; this.previewEndpoint = null; this.exportEndpoint = null; this.fetcher = null; this.exportPayload = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.previewEndpoint = options.previewEndpoint || options.endpoint || null; this.exportEndpoint = options.exportEndpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_IMPORT_PREVIEW', (p) => this.previewImport(p.data || p.item || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_EXPORT_PREPARE', (p) => this.prepareExport(p.items || [], p.type || 'json'))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_IMPORT_EXPORT_RESET', () => this.reset())); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async previewRemote(input = {}) { if (!this.previewEndpoint || !this.fetcher) return this.previewImport(input); const response = await this.fetcher(this.previewEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); if (!response.ok) throw new Error(`Import preview failed with ${response.status}`); const data = await response.json(); this.preview = data.preview || data; return this.preview; }
    previewImport(input = {}) { const rows = typeof input.content === 'string' ? this.parse(input.content, input.type || 'json') : (input.rows || []); const errors = rows.flatMap((row, index) => this.validateRow(row).map((error) => ({ index, error }))); this.preview = { rows, errors, valid: errors.length === 0 }; this.eventBus?.publish?.('IMPORT_PREVIEW_READY', { data: this.preview, timestamp: Date.now() }); return this.preview; }
    async prepareExportRemote(rows = [], type = 'json') { if (!this.exportEndpoint || !this.fetcher) return this.prepareExport(rows, type); const response = await this.fetcher(this.exportEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rows, type }) }); if (!response.ok) throw new Error(`Export prepare failed with ${response.status}`); const data = await response.json(); this.exportPayload = data.export || data; return this.exportPayload; }
    prepareExport(rows = [], type = 'json') { const content = type === 'csv' ? this.toCsv(rows) : JSON.stringify(rows, null, 2); this.exportPayload = { type, content, count: rows.length }; this.eventBus?.publish?.('EXPORT_READY', { type, data: this.exportPayload, timestamp: Date.now() }); return this.exportPayload; }
    parse(content, type) { if (type === 'csv') { const [head, ...lines] = content.trim().split(/\r?\n/); const keys = head.split(',').map((key) => key.trim()); return lines.filter(Boolean).map((line) => Object.fromEntries(line.split(',').map((value, index) => [keys[index], value.trim()]))); } const data = JSON.parse(content || '[]'); return Array.isArray(data) ? data : [data]; }
    validateRow(row) { if (!row || typeof row !== 'object') return ['row must be an object']; return []; }
    toCsv(rows) { if (!rows.length) return ''; const keys = Object.keys(rows[0]); return [keys.join(','), ...rows.map((row) => keys.map((key) => JSON.stringify(row[key] ?? '')).join(','))].join('\n'); }
    reset() { this.preview = null; this.previewEndpoint = null; this.exportEndpoint = null; this.fetcher = null; this.exportPayload = null; }
}
