export class PaymentAdaptersService {
    constructor(eventBus) { this.eventBus = eventBus; this.adapters = new Map(); this.activeFlow = null; this.sessionEndpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.sessionEndpoint = options.sessionEndpoint || options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); for (const adapter of options.adapters || []) this.registerAdapter(adapter); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PAYMENT_ADAPTER_REGISTER', (p) => this.registerAdapter(p.data))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PAYMENT_FLOW_START', (p) => this.startFlow(p.key || p.id, p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PAYMENT_FLOW_RESET', () => this.resetFlow())); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); this.activeFlow = null; }
    registerAdapter(adapter = {}) { if (!adapter.id) return false; const safe = { id: String(adapter.id), label: adapter.label || adapter.id, capabilities: adapter.capabilities || [], createClientState: adapter.createClientState }; this.adapters.set(safe.id, safe); this.eventBus?.publish?.('PAYMENT_ADAPTER_READY', { id: safe.id, data: { label: safe.label, capabilities: safe.capabilities }, timestamp: Date.now() }); return true; }
    async createSession(intent = {}) { if (!this.sessionEndpoint || !this.fetcher) return intent; const response = await this.fetcher(this.sessionEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(intent) }); if (!response.ok) throw new Error(`Payment session failed with ${response.status}`); return response.json(); }
    startFlow(adapterId, intent = {}) { const adapter = this.adapters.get(String(adapterId)); if (!adapter) { this.error(`Unknown payment adapter: ${adapterId}`); return null; } this.activeFlow = { adapterId: adapter.id, status: 'started', clientSecretPresent: Boolean(intent.clientSecret), amount: intent.amount, currency: intent.currency, returnUrl: intent.returnUrl }; this.eventBus?.publish?.('PAYMENT_FLOW_STARTED', { id: adapter.id, data: this.activeFlow, timestamp: Date.now() }); return this.activeFlow; }
    resetFlow() { this.activeFlow = null; }
    error(error) { this.eventBus?.publish?.('PAYMENT_FLOW_ERROR', { error: error?.message || String(error), timestamp: Date.now() }); }
}
