const ALLOWED_TRANSITIONS = { draft: ['review'], review: ['draft', 'scheduled', 'published'], scheduled: ['draft', 'published'], published: ['archived'], archived: [] };

export class ContentWorkflowService {
    constructor(eventBus) { this.eventBus = eventBus; this.items = new Map(); this.endpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); for (const item of options.items || []) this.setItem(item); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CONTENT_WORKFLOW_SET', (p) => this.setItem(p.item || p.data))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CONTENT_WORKFLOW_TRANSITION', (p) => this.transition(p.id, p.type || p.data?.status, p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CONTENT_WORKFLOW_CLEAR', () => this.clear())); this.publish(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async transitionRemote(id, status, data = {}) { if (!this.endpoint || !this.fetcher) return this.transition(id, status, data); const response = await this.fetcher(`${this.endpoint}/${encodeURIComponent(id)}/transition`, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, data }) }); if (!response.ok) throw new Error(`Workflow transition failed with ${response.status}`); const result = await response.json(); return this.setItem(result.item || result); }
    setItem(item = {}) { if (!item.id) return false; const normalized = { id: String(item.id), title: item.title || '', status: item.status || 'draft', assigneeId: item.assigneeId, scheduledAt: item.scheduledAt, data: item.data || {} }; this.items.set(normalized.id, normalized); this.publish(); return normalized; }
    transition(id, status, data = {}) { const current = this.items.get(String(id)); if (!current || !status) return null; const allowed = ALLOWED_TRANSITIONS[current.status] || []; if (!allowed.includes(status)) { this.eventBus?.publish?.('CONTENT_WORKFLOW_ERROR', { id: String(id), error: `Invalid transition ${current.status} -> ${status}`, timestamp: Date.now() }); return null; } const next = { ...current, ...data, status }; this.items.set(String(id), next); this.eventBus?.publish?.('CONTENT_WORKFLOW_TRANSITIONED', { id: String(id), item: next, timestamp: Date.now() }); this.publish(); return next; }
    getItem(id) { return this.items.get(String(id)) || null; }
    clear() { this.items.clear(); this.publish(); }
    publish() { this.eventBus?.publish?.('CONTENT_WORKFLOW_UPDATED', { items: [...this.items.values()], timestamp: Date.now() }); }
}
