export class CmsContentService {
    constructor(eventBus) { this.eventBus = eventBus; this.documents = new Map(); this.fetcher = null; this.endpoint = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.endpoint = options.endpoint || null; for (const doc of options.documents || []) this.put(doc); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CMS_CONTENT_LOAD', (p) => this.load(p.id || p.route || p.url, p))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CMS_CONTENT_PREFETCH', (p) => this.prefetch(p.id || p.route || p.url, p))); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    put(document) { if (!document?.id && !document?.route) return false; const key = document.id || document.route; this.documents.set(key, this.normalize(document)); return true; }
    async load(key, options = {}) { try { const document = this.documents.get(key) || await this.fetchDocument(options.url || this.resolveUrl(key)); if (document) this.put(document); const normalized = document ? this.normalize(document) : null; this.eventBus?.publish?.('CMS_CONTENT_LOADED', { id: key, route: normalized?.route, document: normalized, timestamp: Date.now() }); return normalized; } catch (error) { this.eventBus?.publish?.('CMS_CONTENT_ERROR', { id: key, error: error?.message || String(error), timestamp: Date.now() }); return null; } }
    async prefetch(key, options = {}) { const document = await this.load(key, options); if (document) this.eventBus?.publish?.('CMS_CONTENT_PREFETCHED', { id: key, route: document.route, document, timestamp: Date.now() }); return document; }
    resolveUrl(key) { if (!this.endpoint) return key; const base = this.endpoint.endsWith('/') ? this.endpoint : `${this.endpoint}/`; return `${base}${encodeURIComponent(key)}`; }
    async fetchDocument(url) { if (!this.fetcher) return null; const response = await this.fetcher(url, { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Content load failed with ${response.status}`); return response.json(); }
    normalize(document) { return { id: String(document.id || document.route), type: document.type || 'page', title: document.title || '', route: document.route, locale: document.locale || 'en', blocks: Array.isArray(document.blocks) ? document.blocks : [], meta: document.meta || {}, data: document.data || {} }; }
    get(key) { return this.documents.get(key) || null; }
}
