export class ReviewsService {
    constructor(eventBus) { this.eventBus = eventBus; this.reviews = new Map(); this.pending = new Map(); this.endpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); for (const review of options.reviews || []) this.put(review); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_REVIEWS_LOAD', (p) => this.load(p.items || p.data || []))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_REVIEW_SUBMIT', (p) => this.submit(p.item || p.data))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_REVIEW_RESET', () => this.resetPending())); this.publish(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async loadRemote(targetId) { if (!this.endpoint || !this.fetcher) return this.getReviews(targetId); const url = new URL(this.endpoint, globalThis.location?.origin || 'http://localhost'); if (targetId) url.searchParams.set('targetId', targetId); const response = await this.fetcher(url.toString(), { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Reviews load failed with ${response.status}`); const data = await response.json(); return this.load(Array.isArray(data) ? data : data.items || []); }
    load(reviews = []) { this.reviews.clear(); reviews.forEach((review) => this.put(review)); this.publish(); return this.getReviews(); }
    put(review = {}) { if (!review.id && !review.targetId) return false; const id = String(review.id || `pending-${Date.now()}`); this.reviews.set(id, this.normalize({ ...review, id })); return true; }
    async submitRemote(review = {}) { if (!this.endpoint || !this.fetcher) return this.submit(review); const response = await this.fetcher(this.endpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(review) }); if (!response.ok) throw new Error(`Review submit failed with ${response.status}`); const data = await response.json(); return this.submit(data.review || data); }
    submit(review = {}) { const normalized = this.normalize({ ...review, id: review.id || `optimistic-${Date.now()}`, status: review.status || 'pending' }); this.pending.set(normalized.id, normalized); this.reviews.set(normalized.id, normalized); this.eventBus?.publish?.('REVIEW_SUBMITTED', { id: normalized.id, item: normalized, timestamp: Date.now() }); this.publish(); return normalized; }
    resetPending() { for (const id of this.pending.keys()) this.reviews.delete(id); this.pending.clear(); this.publish(); }
    normalize(review) { return { id: String(review.id), targetId: String(review.targetId || ''), rating: Math.max(1, Math.min(5, Number(review.rating || 1))), title: review.title || '', body: review.body || '', status: review.status || 'published', authorId: review.authorId, data: review.data || {} }; }
    getReviews(targetId) { return [...this.reviews.values()].filter((review) => !targetId || review.targetId === targetId); }
    getSummary(targetId) { const reviews = this.getReviews(targetId); const average = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0; return { count: reviews.length, average }; }
    publish() { this.eventBus?.publish?.('REVIEWS_UPDATED', { items: this.getReviews(), data: this.getSummary(), timestamp: Date.now() }); }
}
