export class AdminAuditLogService {
    constructor(eventBus) { this.eventBus = eventBus; this.entries = []; this.filters = {}; this.endpoint = null; this.exportEndpoint = null; this.fetcher = null; this.sequence = 0; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.endpoint = options.endpoint || null; this.exportEndpoint = options.exportEndpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.entries = (options.entries || []).map((entry) => this.normalize(entry)); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_ADMIN_AUDIT_LOG_LOAD', (p) => this.load(p.items || p.data || []))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_ADMIN_AUDIT_LOG_FILTER', (p) => this.setFilters(p.data || p.filters || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_ADMIN_AUDIT_LOG_EXPORT', (p) => this.export(p.type || 'json'))); this.publish(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async loadRemote(filters = {}) { if (!this.endpoint || !this.fetcher) return this.getFilteredEntries(); const url = new URL(this.endpoint, globalThis.location?.origin || 'http://localhost'); for (const [key, value] of Object.entries(filters)) if (value) url.searchParams.set(key, value); const response = await this.fetcher(url.toString(), { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Audit log load failed with ${response.status}`); const data = await response.json(); return this.load(Array.isArray(data) ? data : data.items || []); }
    load(entries = []) { this.entries = entries.map((entry) => this.normalize(entry)); this.publish(); return this.entries; }
    setFilters(filters = {}) { this.filters = { ...filters }; this.publish(); return this.filters; }
    getFilteredEntries() { return this.entries.filter((entry) => Object.entries(this.filters).every(([key, value]) => !value || entry[key] === value)); }
    async exportRemote(type = 'json') { if (!this.exportEndpoint || !this.fetcher) return this.export(type); const response = await this.fetcher(this.exportEndpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, filters: this.filters }) }); if (!response.ok) throw new Error(`Audit export failed with ${response.status}`); return response.json(); }
    export(type = 'json') { const rows = this.getFilteredEntries(); const content = type === 'csv' ? this.toCsv(rows) : JSON.stringify(rows, null, 2); this.eventBus?.publish?.('ADMIN_AUDIT_LOG_EXPORTED', { type, data: { content, count: rows.length }, timestamp: Date.now() }); return { type, content, count: rows.length }; }
    normalize(entry) { this.sequence += 1; return { id: String(entry.id || `audit-${this.sequence}`), actorId: entry.actorId || 'unknown', action: entry.action || 'unknown', resource: entry.resource || '', severity: entry.severity || 'info', timestamp: entry.timestamp || Date.now(), data: entry.data || {} }; }
    toCsv(rows) { const header = ['id','actorId','action','resource','severity','timestamp']; return [header.join(','), ...rows.map((row) => header.map((key) => JSON.stringify(row[key] ?? '')).join(','))].join('\n'); }
    publish() { this.eventBus?.publish?.('ADMIN_AUDIT_LOG_UPDATED', { items: this.getFilteredEntries(), data: { filters: this.filters }, timestamp: Date.now() }); }
}
