#!/usr/bin/env node
/**
 * create-module.js — module scaffold generator (Tier-2 agent rail).
 *
 * Usage: npm run create:module -- <name>
 *
 * Writes a correct-by-construction module tree that passes certification
 * out of the box (npm run certify:module -- <name>):
 *
 *   src/modules/<name>/
 *     index.js                     manifest + services + contracts export
 *     contracts/<name>-contracts.js  INTENT + state event, canonical rate limits
 *     services/<Name>Service.js    init/destroy + subscription cleanup
 *     README.md                    catalog-only banner + surface table
 *   tests/<name>.test.js           passing skeleton test
 *
 * Follows the captcha module's index conventions (manifest + services map +
 * contracts collection export) so ModuleManager validates the definition.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');

const rawName = process.argv[2];
if (!rawName || !/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(rawName)) {
    console.error('Usage: npm run create:module -- <kebab-case-name>');
    console.error('  Name must be lowercase kebab-case (letters, digits, single dashes).');
    process.exit(1);
}
const name = rawName;
const pascal = name.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('');
const UPPER = name.replace(/-/g, '_').toUpperCase();
const title = name.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ');

const moduleDir = path.join(ROOT, 'src', 'modules', name);
if (fs.existsSync(moduleDir)) {
    console.error(`[create:module] src/modules/${name} already exists.`);
    process.exit(1);
}

const files = {
    [path.join(moduleDir, 'index.js')]: `import { ${pascal}Service } from './services/${pascal}Service.js';
import { ${pascal}Contracts } from './contracts/${name}-contracts.js';

export const manifest = {
    id: '${name}',
    name: '${title} Module',
    version: '1.0.0',
    description: '${title} state, contracts, and service for CSMA',
    dependencies: [],
    services: ['${name}'],
    contracts: Object.keys(${pascal}Contracts)
};

export const services = {
    '${name}': ${pascal}Service
};

export { ${pascal}Service, ${pascal}Contracts };

export const contracts = ${pascal}Contracts;
`,
    [path.join(moduleDir, 'contracts', `${name}-contracts.js`)]: `import { object, string, optional } from '../../../runtime/validation/index.js';

export const ${pascal}Contracts = {
    INTENT_${UPPER}_ADD: {
        version: 1,
        type: 'intent',
        owner: '${name}',
        lifecycle: 'active',
        stability: 'experimental',
        compliance: 'internal',
        description: 'Request to add a ${name} item',
        schema: object({
            title: string(),
            note: optional(string())
        }),
        security: {
            rateLimits: { requests: 30, windowMs: 60000, scope: 'session' }
        }
    },
    ${UPPER}_STATE_CHANGED: {
        version: 1,
        type: 'event',
        owner: '${name}',
        lifecycle: 'active',
        stability: 'experimental',
        compliance: 'internal',
        description: 'Published whenever ${name} items change',
        schema: object({
            reason: string(),
            itemId: optional(string()),
            count: string()
        })
    }
};
`,
    [path.join(moduleDir, 'services', `${pascal}Service.js`)]: `/**
 * ${pascal}Service — scaffold service (generated by create:module).
 *
 * Owns ${name} state and the INTENT_${UPPER}_ADD intent; publishes
 * ${UPPER}_STATE_CHANGED after every mutation. Replace the in-memory store
 * and shape the schemas to the real domain; keep the lifecycle contract
 * (init/destroy with subscription cleanup).
 */

import { uid } from '../../../utils/id.js';

export class ${pascal}Service {
    constructor(eventBus) {
        this.eventBus = eventBus;
        this.items = new Map();
        this.subscriptions = [];
        this.initialized = false;
    }

    init(options = {}) {
        if (this.initialized) return;
        this.initialized = true;
        for (const item of options.items || []) this.add(item);

        this.subscriptions.push(
            this.eventBus?.subscribe?.('INTENT_${UPPER}_ADD', (payload) => {
                const item = this.add({ title: payload?.title, note: payload?.note });
                this.publishState('added', item.id);
            })
        );
    }

    add({ title, note } = {}) {
        const item = { id: uid('${name}'), title: String(title ?? ''), note: note ?? null, createdAt: Date.now() };
        this.items.set(item.id, item);
        return item;
    }

    list() {
        return [...this.items.values()];
    }

    publishState(reason, itemId) {
        this.eventBus?.publish?.('${UPPER}_STATE_CHANGED', {
            reason,
            itemId,
            count: String(this.items.size)
        });
    }

    destroy() {
        for (const unsub of this.subscriptions) {
            try { unsub(); } catch { /* best-effort */ }
        }
        this.subscriptions = [];
        this.initialized = false;
    }
}
`,
    [path.join(moduleDir, 'README.md')]: `# ${title} Module

> **Catalog-only module:** not wired into any demo; not yet certified. Run
> \`npm run certify:module\` before relying on it.

## Purpose

Scaffold generated by \`npm run create:module\`. Owns ${name} state, the
\`INTENT_${UPPER}_ADD\` intent, and the \`${UPPER}_STATE_CHANGED\` state event.
Replace with the real domain.

## Public Surface

| Surface | Details |
|---------|---------|
| Service | \`${name}\` (\`${pascal}Service\`) — init/destroy, intent subscription |
| Contracts | \`INTENT_${UPPER}_ADD\` (rate-limited), \`${UPPER}_STATE_CHANGED\` |
| Exports | \`${pascal}Service\`, \`${pascal}Contracts\` |

## Runtime Integration

Loaded via ModuleManager from the manifest; no dependencies on other modules
(module boundary is enforced by \`npm run security-check\`).

## Tests

\`tests/${name}.test.js\` — init/subscribe, intent→state round trip, destroy.
`,
    [path.join(ROOT, 'tests', `${name}.test.js`)]: `import { describe, it, expect } from 'vitest';
import { EventBus } from '../src/runtime/EventBus.js';
import { ${pascal}Service, ${pascal}Contracts } from '../src/modules/${name}/index.js';

function contractBus() {
    const bus = new EventBus();
    bus.contracts = ${pascal}Contracts;
    return bus;
}

describe('${name} module (scaffold)', () => {
    it('manifest declares the service and contracts', async () => {
        const mod = await import('../src/modules/${name}/index.js');
        expect(mod.manifest.id).toBe('${name}');
        expect(mod.manifest.services).toContain('${name}');
        expect(Object.keys(mod.contracts)).toContain('INTENT_${UPPER}_ADD');
    });

    it('intent add → state changed round trip', () => {
        const bus = contractBus();
        const service = new ${pascal}Service(bus);
        service.init();

        const seen = [];
        bus.subscribe('${UPPER}_STATE_CHANGED', (p) => seen.push(p.reason));

        bus.publish('INTENT_${UPPER}_ADD', { title: 'first' });

        expect(seen).toContain('added');
        expect(service.list()).toHaveLength(1);
        expect(service.list()[0].title).toBe('first');

        service.destroy();
    });

    it('destroy unsubscribes (no state events after)', () => {
        const bus = contractBus();
        const service = new ${pascal}Service(bus);
        service.init();
        service.destroy();

        const seen = [];
        bus.subscribe('${UPPER}_STATE_CHANGED', (p) => seen.push(p));
        bus.publish('INTENT_${UPPER}_ADD', { title: 'ignored' });
        expect(seen).toHaveLength(0);
    });
});
`
};

for (const [file, content] of Object.entries(files)) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, 'utf8');
    console.log(`[create:module] wrote ${path.relative(ROOT, file)}`);
}
console.log(`\\n[create:module] ${name} scaffolded. Next:`);
console.log('  1. Shape contracts/schemas to the real domain');
console.log('  2. npm run generate:events   (refresh events reference)');
console.log('  3. npm run certify:module -- ' + name);
