export class ContentPrefetchService {
    constructor(eventBus) { this.eventBus = eventBus; this.cache = new Map(); this.manifest = {}; this.endpoint = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.manifest = options.manifest || {}; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CONTENT_PREFETCH_ROUTE', (p) => this.prefetchRoute(p.route || p.url, p))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CONTENT_PREFETCH_MANIFEST', (p) => this.loadManifest(p.manifest || p.data || {}))); this.eventBus?.publish?.('CONTENT_PREFETCH_READY', { manifest: this.manifest, timestamp: Date.now() }); if (this.endpoint) this.loadRemoteManifest(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); this.cache.clear(); }
    async loadRemoteManifest() { try { const manifest = await this.fetchResource(this.endpoint); if (manifest && typeof manifest === 'object') this.loadManifest(manifest); } catch (error) { this.eventBus?.publish?.('CONTENT_PREFETCH_ERROR', { url: String(this.endpoint), error: error?.message || String(error), timestamp: Date.now() }); } }
    loadManifest(manifest = {}) { this.manifest = { ...this.manifest, ...manifest }; this.eventBus?.publish?.('CONTENT_PREFETCH_READY', { manifest: this.manifest, timestamp: Date.now() }); return this.manifest; }
    async prefetchRoute(route, options = {}) { if (!route) return null; const target = this.manifest[route] || options.url || route; try { const data = await this.fetchResource(target); this.cache.set(route, { data, timestamp: Date.now() }); this.eventBus?.publish?.('CONTENT_PREFETCH_COMPLETED', { route, url: String(target), data, timestamp: Date.now() }); return data; } catch (error) { this.eventBus?.publish?.('CONTENT_PREFETCH_ERROR', { route, url: String(target), error: error?.message || String(error), timestamp: Date.now() }); return null; } }
    async fetchResource(target) { if (typeof target === 'object') return target; if (!this.fetcher) return null; const response = await this.fetcher(target, { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Prefetch failed with ${response.status}`); const type = response.headers?.get?.('content-type') || ''; return type.includes('json') ? response.json() : response.text(); }
    get(route) { return this.cache.get(route)?.data || null; }
}
