export class PermissionsUIService {
    constructor(eventBus) { this.eventBus = eventBus; this.capabilities = new Set(); this.roles = new Set(); this.rules = new Map(); this.endpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); (options.roles || []).forEach((role) => this.roles.add(role)); (options.capabilities || []).forEach((capability) => this.capabilities.add(capability)); for (const rule of options.rules || []) this.setRule(rule.key || rule.id, rule); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PERMISSIONS_UI_SET', (p) => this.applyState(p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PERMISSIONS_UI_CHECK', (p) => this.check(p.key || p.id, p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_PERMISSIONS_UI_CLEAR', () => this.clear())); this.publish(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async loadEffectivePermissions() { if (!this.endpoint || !this.fetcher) return { roles: [...this.roles], capabilities: [...this.capabilities] }; const response = await this.fetcher(this.endpoint, { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Permissions load failed with ${response.status}`); const data = await response.json(); this.applyState(data); return data; }
    applyState(state = {}) { this.roles = new Set(state.roles || []); this.capabilities = new Set(state.capabilities || []); this.publish(); }
    setRule(key, rule = {}) { if (!key) return false; this.rules.set(String(key), { roles: rule.roles || [], capabilities: rule.capabilities || [] }); return true; }
    check(key, context = {}) { const rule = this.rules.get(String(key)) || context; const allowed = (rule.roles || []).every((role) => this.roles.has(role)) && (rule.capabilities || []).every((capability) => this.capabilities.has(capability)); if (!allowed) this.eventBus?.publish?.('PERMISSIONS_UI_DENIED', { key: String(key), data: { required: rule }, timestamp: Date.now() }); return allowed; }
    clear() { this.roles.clear(); this.capabilities.clear(); this.publish(); }
    publish() { this.eventBus?.publish?.('PERMISSIONS_UI_UPDATED', { data: { roles: [...this.roles], capabilities: [...this.capabilities] }, timestamp: Date.now() }); }
}
