export class CatalogService {
    constructor(eventBus) { this.eventBus = eventBus; this.items = []; this.filters = {}; this.facets = {}; this.selectedItem = null; this.fetcher = null; this.endpoint = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); this.endpoint = options.endpoint || null; this.items = (options.items || []).map((item) => this.normalizeItem(item)); this.facets = this.computeFacets(this.items); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CATALOG_LOAD', (p) => this.load(p.url, p))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CATALOG_FILTER', (p) => this.setFilters(p.filters || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CATALOG_SELECT_ITEM', (p) => this.selectItem(p.id))); this.publishItems(); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async load(url, options = {}) { try { const items = options.items || await this.fetchItems(url || this.endpoint); this.items = items.map((item) => this.normalizeItem(item)); this.facets = this.computeFacets(this.items); this.publishItems(); return this.items; } catch (error) { this.eventBus?.publish?.('CATALOG_ERROR', { error: error?.message || String(error), timestamp: Date.now() }); return []; } }
    async fetchItems(url) { if (!url || !this.fetcher) return []; const response = await this.fetcher(url, { credentials: 'same-origin' }); if (!response.ok) throw new Error(`Catalog load failed with ${response.status}`); const data = await response.json(); return Array.isArray(data) ? data : data.items || []; }
    setFilters(filters = {}) { this.filters = { ...filters }; this.eventBus?.publish?.('CATALOG_FILTERS_CHANGED', { filters: this.filters, items: this.getFilteredItems(), facets: this.facets, timestamp: Date.now() }); return this.filters; }
    selectItem(id) { this.selectedItem = this.items.find((item) => item.id === id) || null; this.eventBus?.publish?.('CATALOG_ITEM_SELECTED', { id, item: this.selectedItem, timestamp: Date.now() }); return this.selectedItem; }
    getFilteredItems() { return this.items.filter((item) => Object.entries(this.filters).every(([key, value]) => value === undefined || value === '' || item[key] === value || (Array.isArray(item[key]) && item[key].includes(value)))); }
    normalizeItem(item) { return { id: String(item.id), type: item.type || 'item', title: item.title || item.name || '', price: item.price, currency: item.currency, categories: item.categories || [], tags: item.tags || [], availability: item.availability || 'unknown', data: item.data || {} }; }
    computeFacets(items) { return { type: [...new Set(items.map((item) => item.type))], availability: [...new Set(items.map((item) => item.availability))], categories: [...new Set(items.flatMap((item) => item.categories || []))] }; }
    publishItems() { this.eventBus?.publish?.('CATALOG_ITEMS_UPDATED', { items: this.items, facets: this.facets, timestamp: Date.now() }); }
}
