export class ChartsService {
    constructor(eventBus) { this.eventBus = eventBus; this.adapters = new Map(); this.datasets = new Map(); this.endpoint = null; this.fetcher = null; this.subscriptions = []; this.initialized = false; }
    init(options = {}) { if (this.initialized) return; this.initialized = true; this.endpoint = options.endpoint || null; this.fetcher = options.fetcher || globalThis.fetch?.bind(globalThis); for (const adapter of options.adapters || []) this.registerAdapter(adapter); for (const dataset of options.datasets || []) this.setData(dataset.id, dataset); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CHART_REGISTER_ADAPTER', (p) => this.registerAdapter(p.data))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CHART_SET_DATA', (p) => this.setData(p.id || p.key, p.data || {}))); this.subscriptions.push(this.eventBus?.subscribe?.('INTENT_CHART_CLEAR', () => this.clear())); }
    destroy() { this.initialized = false; this.subscriptions.splice(0).forEach((u) => u?.()); }
    async query(query = {}) { if (!this.endpoint || !this.fetcher) return null; const response = await this.fetcher(this.endpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(query) }); if (!response.ok) throw new Error(`Metrics query failed with ${response.status}`); const data = await response.json(); if (data.id || query.id) this.setData(data.id || query.id, data); return data; }
    registerAdapter(adapter = {}) { if (!adapter.id) return false; this.adapters.set(String(adapter.id), { id: String(adapter.id), label: adapter.label || adapter.id, render: adapter.render }); this.eventBus?.publish?.('CHART_ADAPTER_READY', { id: String(adapter.id), data: { label: adapter.label || adapter.id }, timestamp: Date.now() }); return true; }
    setData(id, dataset = {}) { if (!id) return false; const normalized = { id: String(id), type: dataset.type || 'series', points: Array.isArray(dataset.points) ? dataset.points : [], summary: dataset.summary || {}, status: dataset.status || 'ready' }; this.datasets.set(String(id), normalized); this.eventBus?.publish?.('CHARTS_UPDATED', { id: String(id), data: normalized, timestamp: Date.now() }); return true; }
    getData(id) { return this.datasets.get(String(id)) || null; }
    formatNumber(value, options = {}) { return new Intl.NumberFormat(options.locale || 'en', options).format(Number(value || 0)); }
    clear() { this.datasets.clear(); this.eventBus?.publish?.('CHARTS_UPDATED', { data: { datasets: [] }, timestamp: Date.now() }); }
}
